import { Task, TaskStatus, TaskPriority, TaskType } from './types';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Reinstalação do Windows - Laboratório 3, PC 12',
    description: 'Computador apresentando lentidão excessiva e erros no sistema. Necessário formatar e reinstalar o Windows 11 Pro junto com os softwares educacionais padrão da escola.',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    type: TaskType.SOFTWARE,
    assignedTo: 'João Silva',
    computerId: 'LAB3-PC12',
    location: 'Laboratório de Informática 3 - PC 12',
    createdAt: new Date('2024-01-15T09:00:00'),
    updatedAt: new Date('2024-01-15T14:30:00'),
    dueDate: new Date('2024-01-17T17:00:00'),
    history: [
      {
        id: '1-1',
        action: 'Tarefa criada',
        description: 'Tarefa aberta pelo sistema de chamados',
        performedBy: 'Maria Santos',
        timestamp: new Date('2024-01-15T09:00:00'),
      },
      {
        id: '1-2',
        action: 'Status alterado',
        description: 'De Pendente para Em Andamento',
        performedBy: 'João Silva',
        timestamp: new Date('2024-01-15T14:30:00'),
      },
    ],
  },
  {
    id: '2',
    title: 'Troca de monitor - Sala de Aula 201',
    description: 'Monitor Samsung 24" com tela piscando e linhas horizontais. Substituir por monitor reserva.',
    status: TaskStatus.PENDING,
    priority: TaskPriority.MEDIUM,
    type: TaskType.HARDWARE,
    assignedTo: 'Pedro Costa',
    computerId: 'SALA201-PC01',
    location: 'Sala de Aula 201 - PC 01',
    createdAt: new Date('2024-01-15T11:00:00'),
    updatedAt: new Date('2024-01-15T11:00:00'),
    dueDate: new Date('2024-01-18T17:00:00'),
    history: [
      {
        id: '2-1',
        action: 'Tarefa criada',
        description: 'Reportado por professor da sala 201',
        performedBy: 'Ana Oliveira',
        timestamp: new Date('2024-01-15T11:00:00'),
      },
    ],
  },
  {
    id: '3',
    title: 'Atualização do Antivírus - Todos os Computadores',
    description: 'Executar atualização em massa do antivírus corporativo em todos os 260 computadores da escola.',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.URGENT,
    type: TaskType.SECURITY,
    assignedTo: 'Carlos Mendes',
    location: 'Todos os Laboratórios e Salas',
    createdAt: new Date('2024-01-14T08:00:00'),
    updatedAt: new Date('2024-01-15T10:00:00'),
    dueDate: new Date('2024-01-16T17:00:00'),
    history: [
      {
        id: '3-1',
        action: 'Tarefa criada',
        description: 'Atualização crítica de segurança',
        performedBy: 'Sistema',
        timestamp: new Date('2024-01-14T08:00:00'),
      },
      {
        id: '3-2',
        action: 'Progresso',
        description: '45% dos computadores atualizados',
        performedBy: 'Carlos Mendes',
        timestamp: new Date('2024-01-15T10:00:00'),
      },
    ],
  },
  {
    id: '4',
    title: 'Configuração de impressora - Biblioteca',
    description: 'Instalar e configurar nova impressora HP LaserJet na biblioteca central. Configurar rede e compartilhamento.',
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.MEDIUM,
    type: TaskType.HARDWARE,
    assignedTo: 'Lucas Ferreira',
    location: 'Biblioteca Central',
    createdAt: new Date('2024-01-13T14:00:00'),
    updatedAt: new Date('2024-01-15T09:00:00'),
    dueDate: new Date('2024-01-15T17:00:00'),
    completedAt: new Date('2024-01-15T09:00:00'),
    history: [
      {
        id: '4-1',
        action: 'Tarefa criada',
        description: 'Nova impressora recebida',
        performedBy: 'Roberta Lima',
        timestamp: new Date('2024-01-13T14:00:00'),
      },
      {
        id: '4-2',
        action: 'Status alterado',
        description: 'De Pendente para Em Andamento',
        performedBy: 'Lucas Ferreira',
        timestamp: new Date('2024-01-14T10:00:00'),
      },
      {
        id: '4-3',
        action: 'Tarefa concluída',
        description: 'Impressora configurada e testada com sucesso',
        performedBy: 'Lucas Ferreira',
        timestamp: new Date('2024-01-15T09:00:00'),
      },
    ],
  },
  {
    id: '5',
    title: 'Problema de conectividade Wi-Fi - Bloco C',
    description: 'Alunos e professores reportando queda constante de sinal Wi-Fi no Bloco C. Investigar ponto de acesso.',
    status: TaskStatus.PENDING,
    priority: TaskPriority.HIGH,
    type: TaskType.NETWORK,
    assignedTo: 'André Souza',
    location: 'Bloco C - 2º e 3º Andar',
    createdAt: new Date('2024-01-15T07:30:00'),
    updatedAt: new Date('2024-01-15T07:30:00'),
    dueDate: new Date('2024-01-16T12:00:00'),
    history: [
      {
        id: '5-1',
        action: 'Tarefa criada',
        description: 'Múltiplos relatos de problemas de rede',
        performedBy: 'Sistema de Monitoramento',
        timestamp: new Date('2024-01-15T07:30:00'),
      },
    ],
  },
  {
    id: '6',
    title: 'Instalação Microsoft Office 365 - Laboratório 1',
    description: 'Licença renovada. Atualizar Microsoft Office 365 em todos os 30 computadores do Laboratório 1.',
    status: TaskStatus.PENDING,
    priority: TaskPriority.LOW,
    type: TaskType.SOFTWARE,
    assignedTo: 'Fernanda Rodrigues',
    location: 'Laboratório de Informática 1',
    createdAt: new Date('2024-01-15T13:00:00'),
    updatedAt: new Date('2024-01-15T13:00:00'),
    dueDate: new Date('2024-01-22T17:00:00'),
    history: [
      {
        id: '6-1',
        action: 'Tarefa criada',
        description: 'Renovação de licença institucional',
        performedBy: 'Coordenação de TI',
        timestamp: new Date('2024-01-15T13:00:00'),
      },
    ],
  },
  {
    id: '7',
    title: 'Manutenção preventiva - Servidor Principal',
    description: 'Realizar manutenção preventiva mensal do servidor principal: verificação de logs, atualizações de segurança, backup completo.',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.URGENT,
    type: TaskType.MAINTENANCE,
    assignedTo: 'Ricardo Alves',
    location: 'Sala do Servidor',
    createdAt: new Date('2024-01-14T09:00:00'),
    updatedAt: new Date('2024-01-15T16:00:00'),
    dueDate: new Date('2024-01-15T18:00:00'),
    history: [
      {
        id: '7-1',
        action: 'Tarefa criada',
        description: 'Manutenção preventiva agendada',
        performedBy: 'Sistema',
        timestamp: new Date('2024-01-14T09:00:00'),
      },
      {
        id: '7-2',
        action: 'Progresso',
        description: 'Backup em andamento (75% concluído)',
        performedBy: 'Ricardo Alves',
        timestamp: new Date('2024-01-15T16:00:00'),
      },
    ],
  },
  {
    id: '8',
    title: 'Troca de teclado - Secretaria',
    description: 'Teclado com várias teclas travadas. Substituir por teclado novo.',
    status: TaskStatus.COMPLETED,
    priority: TaskPriority.LOW,
    type: TaskType.HARDWARE,
    assignedTo: 'Paulo Henrique',
    computerId: 'SEC-PC05',
    location: 'Secretaria - PC 05',
    createdAt: new Date('2024-01-14T10:00:00'),
    updatedAt: new Date('2024-01-14T15:00:00'),
    dueDate: new Date('2024-01-14T17:00:00'),
    completedAt: new Date('2024-01-14T15:00:00'),
    history: [
      {
        id: '8-1',
        action: 'Tarefa criada',
        description: 'Reportado pela secretária',
        performedBy: 'Sistema de Chamados',
        timestamp: new Date('2024-01-14T10:00:00'),
      },
      {
        id: '8-2',
        action: 'Tarefa concluída',
        description: 'Teclado substituído com sucesso',
        performedBy: 'Paulo Henrique',
        timestamp: new Date('2024-01-14T15:00:00'),
      },
    ],
  },
  {
    id: '9',
    title: 'Bloqueio de sites não autorizados - Firewall',
    description: 'Atualizar lista de sites bloqueados no firewall conforme nova política de uso aceitável.',
    status: TaskStatus.PENDING,
    priority: TaskPriority.MEDIUM,
    type: TaskType.SECURITY,
    assignedTo: 'Carlos Mendes',
    location: 'Servidor de Rede',
    createdAt: new Date('2024-01-15T10:00:00'),
    updatedAt: new Date('2024-01-15T10:00:00'),
    dueDate: new Date('2024-01-19T17:00:00'),
    history: [
      {
        id: '9-1',
        action: 'Tarefa criada',
        description: 'Nova política de uso aprovada',
        performedBy: 'Direção',
        timestamp: new Date('2024-01-15T10:00:00'),
      },
    ],
  },
  {
    id: '10',
    title: 'Instalação de projetor - Auditório',
    description: 'Instalar e configurar novo projetor Epson no auditório. Testar conexão com computadores e sistema de som.',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    type: TaskType.HARDWARE,
    assignedTo: 'Lucas Ferreira',
    location: 'Auditório Principal',
    createdAt: new Date('2024-01-14T13:00:00'),
    updatedAt: new Date('2024-01-15T11:00:00'),
    dueDate: new Date('2024-01-17T17:00:00'),
    history: [
      {
        id: '10-1',
        action: 'Tarefa criada',
        description: 'Novo equipamento recebido',
        performedBy: 'Coordenação de Eventos',
        timestamp: new Date('2024-01-14T13:00:00'),
      },
      {
        id: '10-2',
        action: 'Progresso',
        description: 'Projetor instalado, em testes finais',
        performedBy: 'Lucas Ferreira',
        timestamp: new Date('2024-01-15T11:00:00'),
      },
    ],
  },
  {
    id: '11',
    title: 'Limpeza interna dos computadores - Laboratório 2',
    description: 'Realizar limpeza interna (poeira) dos 25 computadores do Laboratório 2 para evitar superaquecimento.',
    status: TaskStatus.PENDING,
    priority: TaskPriority.LOW,
    type: TaskType.MAINTENANCE,
    assignedTo: 'Pedro Costa',
    location: 'Laboratório de Informática 2',
    createdAt: new Date('2024-01-12T09:00:00'),
    updatedAt: new Date('2024-01-12T09:00:00'),
    dueDate: new Date('2024-01-26T17:00:00'),
    history: [
      {
        id: '11-1',
        action: 'Tarefa criada',
        description: 'Manutenção preventiva trimestral',
        performedBy: 'Sistema',
        timestamp: new Date('2024-01-12T09:00:00'),
      },
    ],
  },
  {
    id: '12',
    title: 'Erro no sistema de chamados',
    description: 'Usuários reportando erro ao tentar abrir novos chamados pelo portal web. Investigar e corrigir.',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.URGENT,
    type: TaskType.SOFTWARE,
    assignedTo: 'Ricardo Alves',
    location: 'Sistema de Chamados',
    createdAt: new Date('2024-01-15T08:00:00'),
    updatedAt: new Date('2024-01-15T14:00:00'),
    dueDate: new Date('2024-01-15T18:00:00'),
    history: [
      {
        id: '12-1',
        action: 'Tarefa criada',
        description: 'Erro crítico reportado por múltiplos usuários',
        performedBy: 'Sistema de Monitoramento',
        timestamp: new Date('2024-01-15T08:00:00'),
      },
      {
        id: '12-2',
        action: 'Investigação',
        description: 'Erro identificado no módulo de autenticação',
        performedBy: 'Ricardo Alves',
        timestamp: new Date('2024-01-15T14:00:00'),
      },
    ],
  },
];

export const teamMembers = [
  { id: '1', name: 'João Silva', avatar: 'JS', role: 'Técnico de TI Senior' },
  { id: '2', name: 'Pedro Costa', avatar: 'PC', role: 'Técnico de Hardware' },
  { id: '3', name: 'Carlos Mendes', avatar: 'CM', role: 'Especialista em Redes' },
  { id: '4', name: 'Lucas Ferreira', avatar: 'LF', role: 'Técnico de Infraestrutura' },
  { id: '5', name: 'Fernanda Rodrigues', avatar: 'FR', role: 'Técnica de Software' },
  { id: '6', name: 'André Souza', avatar: 'AS', role: 'Especialista em Redes' },
  { id: '7', name: 'Ricardo Alves', avatar: 'RA', role: 'Administrador de Sistemas' },
  { id: '8', name: 'Paulo Henrique', avatar: 'PH', role: 'Técnico de Suporte' },
];

export const getMetrics = () => {
  return {
    pending: mockTasks.filter(t => t.status === TaskStatus.PENDING).length,
    inProgress: mockTasks.filter(t => t.status === TaskStatus.IN_PROGRESS).length,
    completed: mockTasks.filter(t => t.status === TaskStatus.COMPLETED).length,
    cancelled: mockTasks.filter(t => t.status === TaskStatus.CANCELLED).length,
    urgent: mockTasks.filter(t => t.priority === TaskPriority.URGENT).length,
    total: mockTasks.length,
  };
};

export const getUrgentTasks = () => {
  return mockTasks
    .filter(t => t.priority === TaskPriority.URGENT && t.status !== TaskStatus.COMPLETED)
    .sort((a, b) => a.dueDate!.getTime() - b.dueDate!.getTime());
};

export const getRecentTasks = (limit = 5) => {
  return mockTasks
    .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
    .slice(0, limit);
};
